import { Inter } from "next/font/google";
import "./globals.css";
import ProviderSession from "./serverpage/session/ProviderSession";

import ApolloProviderLayout from "./serverpage/apollo/ApolloProviderLayout";
import MainLayout from "./(layout)/MainLayout";
import { Provider } from "react-redux";
import { store } from "../../redux/store";
import CheckAuth from "../../middleware/CheckAuth";
import ListenToast from "../../middleware/ListenToast";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ApolloProviderLayout>
        <ProviderSession>
          <body className={inter.className}>
            <CheckAuth>
              <MainLayout>{children}</MainLayout>
            </CheckAuth>
          </body>
        </ProviderSession>
      </ApolloProviderLayout>
    </html>
  );
}
