import { Inter } from "next/font/google";
import "./globals.css";
import ProviderSession from "./serverpage/session/ProviderSession";

import ApolloProviderLayout from "./serverpage/apollo/ApolloProviderLayout";
import MainLayout from "./(layout)/MainLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ApolloProviderLayout>
        <ProviderSession>
          <MainLayout>
            <body className={inter.className}>{children}</body>
          </MainLayout>
        </ProviderSession>
      </ApolloProviderLayout>
    </html>
  );
}
